### ISSUE TITLE
Nag managers about actionable but unactioned security bugs

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbot#1604]
We should send emails to managers about actionable but unactioned security bugs in their team components.

**Comment by marco-c** [comment]
It looks like this won't be needed any time soon because people are already acting on these bugs. Let's move it to the backlog and revisit in the future.

**Comment by suhaibmujahid** [comment]
I asked @joewalker some time ago if this is still needed. He will let us know.

**Comment by joewalker** [comment]
I think we can say that we don't need this feature at the moment. I'd be happy for us to close it rather than moving it to the backlog.

Thank-you!
