### ISSUE TITLE
Notify triage owners when performing a rotation

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1606]
When rotation a triage owner on Bugzilla, we could notify both of the new and the old triage owner to inform them about the switch. The email could include the list of bugs that are still not triaged on the rotation day.

We could have one email per team or one email per every two triagers. The manager could be in the CC.

@marco-c wdyt?

**Comment by marco-c** [comment]
Makes sense to me, maybe without manager in CC to reduce noise for them.

**Comment by marco-c** [comment]
And instead of the list of bugs, we could just point to the triage center (https://mozilla.github.io/triage-center/?component=COMPONENT1&component=COMPONENT2).

The only problem I see here is if a team has a very quick rotation, it'd be painful to have daily notifications.

**Comment by suhaibmujahid** [comment]
> And instead of the list of bugs, we could just point to the triage center (https://mozilla.github.io/triage-center/?component=COMPONENT1&component=COMPONENT2).

The list in the email can be a reference for what bugs are leftover. This can could work as an encouragement to pass a shorter list. We could replace the list with a Bugzilla query of bugs that were untriaged at that period. 

We still can point to the triage center, but I don't think it supports querying untriaged bugs at a specific period.

> The only problem I see here is if a team has a very quick rotation, it'd be painful to have daily notifications.

I agree. We want to avoid unnecessary emails.

**Comment by marco-c** [comment]
We could start with the Core::General triage, whre the rotations are weekly and where a notification could be nice since the triagers are in different teams.

**Comment by globau** [comment]
I'd prefer that we just had a simple notification of the change of triage ownership with a link to [bugdash](https://bugdash.moz.tools/); no list of bugs.
This reduces the amount of places where the definition of "triaged" lives, and encourages the triage owner to visit the triage dashboard.

> This can could work as an encouragement to pass a shorter list.

This will be immediate obvious on the first trip to bugdash, no need to replicate in email.
