### ISSUE TITLE
Update the Readme file

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1853]
Examples:
- Dryrun command
- Cronjob
- Configs

**Comment by suhaibmujahid** [comment]
You could update that. But we have other things that need to be updated as well. I can take care of the rest.

**Comment by sosa-e** [comment]
Cool, I updated the cloning command on my machine. It should update when I push updates for #1437

**Comment by suhaibmujahid** [comment]
> Cool, I updated the cloning command on my machine. It should update when I push updates for #1437

@sosa-e Thank you! It will be better to have independent changes in separate pull requests.
