### ISSUE TITLE
Temporarily disable needinfo about missing severity for bugs imported by Move to Bugzilla add-on

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1889]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1813916

This should be re-enabled after 2023-06-01

cc @cpeterso

**Comment by cpeterso** [comment]
@suhaibmujahid - At your convenience, you can re-enable my needinfos about bugs with missing severity. No rush! I've reassigned component triage ownership to other people on my team, so I don't expect to receive any of these severity needinfos. 😁
