### ISSUE TITLE
[patch_closed_bug] Avoid commenting when a new attached revision is for uplifting

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1953]
> **Note**
> Reported by @moztcampbell 

Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1821959#c19

> @dsmithpadilla:
> Normally, the bug is closed, but when uplifted in the current process we simply add the uplift link to the already attached patch. However, in the new uplift pilot once it lands in central and gets closed, the developer actually opens a new patch to beta or release or esr which will trigger the bot to think they attached a new patch to a closed bug.

**Comment by marco-c** [comment]
Also https://bugzilla.mozilla.org/show_bug.cgi?id=1818762#c27

**Comment by suhaibmujahid** [comment]
The tool does not comment when the new patch has an uplift request. However, the new uplift pilot workflow does not add approval flags (i.e., `approval-mozilla-*`) to the uplift patches.

https://github.com/mozilla/relman-auto-nag/blob/2989185115d608c87ce2c67180a5da0629ec873e/auto_nag/scripts/patch_closed_bug.py#L54-L57

**Comment by suhaibmujahid** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1825961 to follow up on identifying uplift patches. We could identify the uplift patches by querying them on Phabrecator, which will add unnecessary overhead. It will be better to have a flag or something on the Bugzilla attachments themselves.

**Comment by suhaibmujahid** [comment]
Since [bug 1825961](https://bugzilla.mozilla.org/show_bug.cgi?id=1825961) is already deployed. We should drop the workaround in https://github.com/mozilla/bugbot/pull/2011. If the dry-run returns the expected results, we can close this as completed.

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid what's the status here? The patches referenced have all merged/landed, AFAICT - but this is still happening, cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1842547#c15.

This is a new regression in the new uplift workflow. I reopened [bug 1825961](https://bugzilla.mozilla.org/show_bug.cgi?id=1825961) to follow up on the issue. In the meantime, I have also submitted a PR (i.e., #2168) to restore the workaround to avoid spamming the bugs.
