### ISSUE TITLE
Use new access severity field in Bugzilla instead of whiteboard tag

### ISSUE THREAD

**Issue by jcsteh** [mozilla/bugbot#2069]
We're [migrating](https://bugzilla.mozilla.org/show_bug.cgi?id=1829061) the [access-s] whiteboard tags in Bugzilla to have a dedicated dropdown field. BugBot will need to be updated accordingly.

I'm not quite sure how best to coordinate the timing of this. The Bugzilla migration is ready, but we're holding on executing it. Should the Bugzilla migration wait until the BugBot change lands or should we do it the other way around? I'm not too concerned if we miss a couple of bugs - we can pick those up manually - but it'd be good if we can have these happen within a few days of each other at worst.

Thanks.

**Comment by suhaibmujahid** [comment]
> I'm not quite sure how best to coordinate the timing of this.

It will be better to have the BugBot changes deployed first. I will prioritize working on this today. We could coordinate deploying BugBot changes and Bugzilla migration on the same day.

Alternatively, we can make BugBot support both simultaneously (the Whiteboard Tags and Project Flags). This way, once we deploy the BugBot changes, the Bugzilla migration can be performed anytime. Once the Bugzilla migration is done, we drop the support for the Whiteboard Tags.

**Comment by jcsteh** [comment]
I'm happy to go with whatever makes things easier for both teams. As I noted, manually triaging a few bugs that get missed in any migration is not a big deal; we don't get many each day.
