### ISSUE TITLE
Bugbot doesn't prompt patch authors for approval requests in some mobile products

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/bugbot#2080]
As far as I can tell, at least the Fenix product isn't prompting users for uplift requests for fixed bugs affecting Beta. We should confirm that the Fenix, Focus, and GeckoView products are all included in that.

**Comment by suhaibmujahid** [comment]
Could you please share an example?

**Comment by rvandermeulen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1829361
https://bugzilla.mozilla.org/show_bug.cgi?id=1830398

**Comment by suhaibmujahid** [comment]
Fenix, Focus, and GeckoView are included in the list of supported products. However, for uplifts, the bot currently monitors only bugs with Phabricator patches: https://github.com/mozilla/bugbot/blob/0ce9ee2d406233cb49d78910747b1506a412a60c/bugbot/rules/uplift_beta.py#L122-L125

I will add support to GitHub pull requests.
