### ISSUE TITLE
Please enable severity conversion on the "Release Engineering" product

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla/bugbot#2092]
Hello there! 👋 

The Release Engineering team is catching up on bug triage. One of the things we have to do is to convert the old severity into new one. After chatting with @marco-c, I understand we can leverage bugbot to do it. Would it be possible to get the [Release Engineering](https://bugzilla.mozilla.org/describecomponents.cgi?product=Release%20Engineering) product triaged by bugbot? 

I'm not sure if there's more information needed. Feel free to ask me 🙂

**Comment by suhaibmujahid** [comment]
> Would it be possible to get the [Release Engineering](https://bugzilla.mozilla.org/describecomponents.cgi?product=Release%20Engineering) product triaged by bugbot?

See https://github.com/mozilla/bugbot/pull/2089#pullrequestreview-1452438657. Should we enable all BugBot rules for the "Release Engineering" product? This will include needinfo about missing severity, notify the regression author and many others (full list https://wiki.mozilla.org/BugBot). For sure many of the bot rules will not be applicable even after enabling them (e.g., ask about uplift, unless the fx status flag was set 😉).

**Comment by suhaibmujahid** [comment]
@dklawren could you please re-run your migration script (https://github.com/mozilla-bteam/bmo/pull/1929) on the "Release Engineering" product. I will enable BugBot to handle the rest.

**Comment by dklawren** [comment]
> @dklawren could you please re-run your migration script ([mozilla-bteam/bmo/pull/1929](https://github.com/mozilla-bteam/bmo/pull/1929)) on the "Release Engineering" product. I will enable BugBot to handle the rest.

Done

**Comment by JohanLorenzo** [comment]
Thank you all for acting so quickly on this! I'm sorry it took me some time to get back to you all. I chatted with the whole team. Everyone is on board to enable all features of BugBot on the "Release Engineering" product 😃👍 

Before doing so, I heard you all have a dry run mode that shows what going to be changed. Would it be possible to get this output first, @suhaibmujahid?

**Comment by suhaibmujahid** [comment]
> Before doing so, I heard you all have a dry run mode that shows what going to be changed. Would it be possible to get this output first, @suhaibmujahid?

Yes, it is doable. The dry-run shows the output of a specific rule (example https://github.com/mozilla/bugbot/pull/2089#issuecomment-1569321410). In this case, we need to run it for all rules (we have more than 70 rules).

_Next step:_ I will open a PR to enable all rules of BugBot and post there the outputs of the dry-run.
