### ISSUE TITLE
BugBot shouldn't nag for unlanded patches that have reminder- whiteboard tags

### ISSUE THREAD

**Issue by gijsk** [mozilla/bugbot#2096]
Especially for bugs split off from security ones where the tests need to land substantially later than the original patch, it's not uncommon to have r+'d test patches sit for a month or two. I tend to use `[reminder-test <date>]` to get the bot to tell me when it's time to land them.

Unfortunately, the bot also needinfos me and the reviewer 2 weeks after the patches have been r+'d (and perhaps repeatedly after that? I haven't yet waited that out) to ask when we're landing the patches. It would be nice if it didn't.

**Comment by suhaibmujahid** [comment]
Thank you @gijsk for reporting this. The suggestion seems sound to me. Could you please share an example of a bug with such a case?

**Comment by gijsk** [comment]
@suhaibmujahid https://bugzilla.mozilla.org/show_bug.cgi?id=1832266 :-)
