### ISSUE TITLE
Unify the way we check for security keywords

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbot#2099]
NIT: in two other rules we check security keywords in a different approach, it will be nice to unify that (I think the approach that your using in this PR is more readable):

https://github.com/mozilla/bugbot/blob/f6272f4cef19888b28590269079404691c058779/bugbot/rules/crash_small_volume.py#L118

https://github.com/mozilla/bugbot/blob/f6272f4cef19888b28590269079404691c058779/bugbot/rules/security_unhide_dups.py#L51

_Originally posted by @suhaibmujahid in https://github.com/mozilla/bugbot/pull/2098#discussion_r1219524158_

**Comment by ReticentFacade** [comment]
@marco-c Hi, is it still open? I'd like to contribute.

**Comment by suhaibmujahid** [comment]
> is it still open? I'd like to contribute.

@ReticentFacade Yes, feel free to submit a PR.

**Comment by shubham-s-del** [comment]
@suhaibmujahid @marco-c - I have created a fix. The automated test suite - bugbot-tests seems to pass. 

Please let me know what the next steps would be. Is there any other dev-test that I should be doing here?
