### ISSUE TITLE
Add the `regression` keyword when filing a crash bug with a non-empty `Regressed By` filed

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2153]

**Comment by marco-c** [comment]
I wonder if we could add the keyword in other cases too. E.g. can we detect that a crash is new? In theory if we haven't seen it before it is new, though there are cases where the crash just changes signature, so it's not really a rule.

**Comment by suhaibmujahid** [comment]
I agree, but this could be a bit noisy in case of false positives. If the regression got identified manually at some point later, the keyword will be automatically added.
