### ISSUE TITLE
Missing space in bugbot blurb for beta uplift

### ISSUE THREAD

**Issue by dholbert** [mozilla/bugbot#2194]
BugBot's comment [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1829016#c14) had a missing space between sentences: `approval.Also,`
```
    If yes, please nominate the patch for beta approval.Also, don't [...]
```

Probably we need to update some string in the bugbot code to include a space between those sentences.

**Comment by suhaibmujahid** [comment]
Daniel, thank you for reporting this! It should be fixed by #2195.
