### ISSUE TITLE
bugbot should not close bugs as incomplete just because the reporter never replies to a needinfo

### ISSUE THREAD

**Issue by dholbert** [mozilla/bugbot#2235]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1820246#c6

We have a testcase there, we've reproduced the bug, so the bug is in-no-way incomplete.

We happened to ask the reporter a low-stakes question that they never replied to, and bugbot picked up on this and closed the bug as incomplete.  ("A needinfo is requested from the reporter, however, the reporter is inactive on Bugzilla. Closing the bug as incomplete.")

This is too severe; we need to relax this bugbot logic or we may end up with actionable-but-currently-unresourced bugs getting closed as incomplete inadvertently.

**Comment by dholbert** [comment]
I see - yeah, we should have changed bug 1820246 to CONFIRMED earlier on.  I think the current bug-closing rule makes sense if it's only applied to unconfirmed bugs, yeah.

It would help if the bug-closing message changed to reflect that, though.   I think the reasonable intent of the rule is "we haven't yet been able to confirm the bug, and now we've lost touch with the reporter, so now we can't do much with it"; and the current wording doesn't get that idea across.

The current wording is:
> A needinfo is requested from the reporter, however, the reporter is inactive on Bugzilla. Closing the bug as incomplete.

Maybe better:
> A needinfo is requested from the reporter, however, the reporter is inactive on Bugzilla. Given that the bug is still UNCONFIRMED, closing the bug as incomplete.

**Comment by dholbert** [comment]
i.e. I don't think we need to change the logic after all, but we should clarify the wording, possibly with that "Maybe better" text or something similar. How does that sound @suhaibmujahid ?

**Comment by suhaibmujahid** [comment]
Sounds good to me! I will update the comment text.
