### ISSUE TITLE
Triage owners don't receive daily triage emails as expected

### ISSUE THREAD

**Issue by hsinyi** [mozilla/bugbot#2277]
We have two triage owners for DOM Core triage rotation this week. However, only one of the triage owners received the email.

It used to work before, in August 2023. But something seems wrong then.

**Comment by suhaibmujahid** [comment]
I downloaded the calendar and opened it locally. It seems that only one person was appointed for this week:

<img width="751" alt="image" src="https://github.com/mozilla/bugbot/assets/4151357/3a3ee717-f74d-47ef-bfc2-2fbabb669dab">


August 4th was the last time two persons were triage owners at the same time:

<img width="751" alt="image" src="https://github.com/mozilla/bugbot/assets/4151357/ae4a1f6a-0f35-487f-b8a6-2b4dbebc077c">

If you add another person, the bot should reflect the changes on the calendar.


@hsinyi do you see the same events on the calendar from your end?

**Comment by hsinyi** [comment]
Hi Suhaib, thank you for the investigation. I realized I made something
wrong in the triage invite setting for the second person. I made changes
already so hopefully this would be resolved. Again, I am sorry for wasting
your time.

**Comment by hsinyi** [comment]
Hi Suhaib, I confirmed the issue is resolved. Thank you.

**Comment by suhaibmujahid** [comment]
Glad to help!
