### ISSUE TITLE
Don't nag for a regression when the bug is blocked by a meta QA bug

### ISSUE THREAD

**Issue by calixteman** [mozilla/bugbot#2289]
For example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1868121#c1

From Marco:
```
 a meta QA bug is always for new features
```

**Comment by benjaminmah** [comment]
This rule has been [removed since 2024-02-13](https://wiki.mozilla.org/BugBot), so would I be able to close this issue @calixteman @suhaibmujahid?

**Comment by marco-c** [comment]
Yes, makes sense!
