### ISSUE TITLE
Avoid bugbot spam when folks say "Regression range: not a regression"

### ISSUE THREAD

**Issue by dholbert** [mozilla/bugbot#2338]
I've noticed a pattern with bugbot making noise on bugs, along these lines:
- Comment 0 contains something like:
> Regression range
>    Not a regression since this is reproducible on old Nightly build from 2024-01-13 where this feature officially landed.

- And then bugbot chimes in saying e.g. (where :bmaris was the reporter here):
> :bmaris, if you think that's a regression, could you try to find a regression range using for example [mozregression](https://wiki.mozilla.org/Auto-tools/Projects/Mozregression)?

This seems to happen in many similar bugs and just creates noise/busy-work for the reporter to have to reply or clarify the situation (or ignore it and hope that nobody else is confused by the bot).

Could we make bugbot smarter to avoid this?  I'm not sure if it's keying off of the phrase "regression range" or just the word "regression" or something else, but whatever it is, maybe we could extend it to detect the exact phrase "not a regression" and avoid this nag if that's present?

**Comment by dholbert** [comment]
Some examples where this occurred:
https://bugzilla.mozilla.org/show_bug.cgi?id=1878038
https://bugzilla.mozilla.org/show_bug.cgi?id=1878663
https://bugzilla.mozilla.org/show_bug.cgi?id=1876558

(Basically every dependency of metabug https://bugzilla.mozilla.org/show_bug.cgi?id=1848157 )

**Comment by bogdanmaris** [comment]
Also maybe adding a yes/no/-- field in bugzilla, similar with "Has STR:" could help bugbug making less noise in bugs, but people should use the new field though, just a thought.

**Comment by marco-c** [comment]
> Could you share what precisely is summoning the bot in this situation? (Is it the phrase "regression range" in the first comment, for example? Or in any comment? Or just the word "regression"?)

The bot is adding the comment on any new defect which has "Has STR" set to true and has no regression range: https://github.com/mozilla/bugbot/blob/master/bugbot/rules/has_str_no_range.py.

> Would it be possible to add a some additional logic to the current rule (e.g. maybe searching for the exact phrase "not a regression" in the comment that activates the bot and avoiding the nag if that's present)? If so, I think that would be a nice quality-of-life improvement here.

The rule was excluding softvision emails, perhaps an easy fix is to just exclude all mozilla emails, this should cover most cases.

**Comment by suhaibmujahid** [comment]
> The rule was excluding softvision emails, perhaps an easy fix is to just exclude all mozilla emails, this should cover most cases.

Many Mozilla employees use personal emails for Bugzilla, so this will not solve it completely.

Alternatively, as suggested by @dholbert, we could exclude bugs with `\n**Regression range**\n* Not a regression` in the bug description (i.e., comment 0). We could use regex to tolerate some flexibility in whitespaces.

**Comment by dholbert** [comment]
> The bot is adding the comment on any new defect which has "Has STR" set to true and has no regression range:

Aha, that's really good to know. I was guessing that the bot was keying off of the presence of the word "regression" or similar in a bug comment (which would make this much more of a footgun), but that was my mistake in guessing at the bot's reasoning. :)

**Comment by bogdanmaris** [comment]
> The rule was excluding softvision emails, perhaps an easy fix is to just exclude all mozilla emails, this should cover most cases.

We (from ex Softvision, current Cognizant) are not using the softvision.ro/.com emails anymore for Bugzilla, we switched to using our mozilla emails as well so that rule can be removed.
