### ISSUE TITLE
Some Intermittent bugs that could be closed are not closed.

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbot#2381]
It seems that some bugs escape from the intermittent bot's rules and stay open for longer than expected.

Some examples:
https://bugzilla.mozilla.org/show_bug.cgi?id=1814756
https://bugzilla.mozilla.org/show_bug.cgi?id=1800348
https://bugzilla.mozilla.org/show_bug.cgi?id=1770332
https://bugzilla.mozilla.org/show_bug.cgi?id=1756354

**Comment by marco-c** [comment]
See also #1992.

**Comment by marco-c** [comment]
Other two examples shared by @sylvestre:
https://bugzilla.mozilla.org/show_bug.cgi?id=966804
https://bugzilla.mozilla.org/show_bug.cgi?id=987493

**Comment by marco-c** [comment]
> Other two examples shared by @sylvestre: https://bugzilla.mozilla.org/show_bug.cgi?id=966804 https://bugzilla.mozilla.org/show_bug.cgi?id=987493

These two are not closed because of https://github.com/mozilla/bugbot/blob/888e06c65f02f66a250f37321ff89fd83cbb05b5/bugbot/rules/close_intermittents.py#L61-L63 and https://github.com/mozilla/bugbot/blob/888e06c65f02f66a250f37321ff89fd83cbb05b5/bugbot/rules/close_intermittents.py#L66-L67.

**Comment by marco-c** [comment]
> It seems that some bugs escape from the intermittent bot's rules and stay open for longer than expected.
> 
> Some examples:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1814756
> https://bugzilla.mozilla.org/show_bug.cgi?id=1800348
> https://bugzilla.mozilla.org/show_bug.cgi?id=1770332
> https://bugzilla.mozilla.org/show_bug.cgi?id=1756354

The first and the third should be covered by #2485.
The second and fourth should be covered by #1994 and #1993.

The leave-open case should be covered by #2487.
