### ISSUE TITLE
 Web Compatibility bugs do not get release management updates

### ISSUE THREAD

**Issue by DonalMe** [mozilla/bugbot#2533]
The webcompat team uses bugs in the `Web Compatibility` product to track bugs. These may include regressions.

Example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1929199 has a regressor. 
However, bugbot did not update the release tracking and it did not add a need-info on the regressor assignee.

**Comment by suhaibmujahid** [comment]
The `Web Compatibility` product currently is not on the list of included products: https://github.com/mozilla/bugbot/blob/4afbef850b2bb8d22c8e926beb421fd44aac7328/configs/rules.json#L37-L56


I will include it, which will enable all BugBot rules on the `Web Compatibility` product.

**Comment by marco-c** [comment]
It looks like it was disabled on purpose in #2104. Maybe we should enable selected rules? WDYT @denschub?

**Comment by DonalMe** [comment]
If can do the specific rules then that would be ok for relman. 
Want to call out recently (relatively recently?) it was decided to track fixes in the web compact product. 
We lost the automation the bugbot adds and it is critical for relman.

**Comment by marco-c** [comment]
@denschub what do you think of doing this: enable everything, then when you see something that should be disabled we disable it.
This way we don't miss anything important, and you only suffer the noise for a few weeks until we disable everything that is not needed.

**Comment by denschub** [comment]
Works for me. :)
